language: node_js
node_js:
  - 16
  
services:
  - docker
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed raoulkuate/udagram-api-feed:v2
  - docker tag udagram-api-user raoulkuate/udagram-api-user:v2
  - docker tag udagram-frontend raoulkuate/udagram-frontend:v3
  - docker tag udagram-reverseproxy raoulkuate/udagram-reverseproxy:v3
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push raoulkuate/udagram-api-feed:v2
  - docker push raoulkuate/udagram-api-user:v2
  - docker push raoulkuate/udagram-frontend:v3
  - docker push raoulkuate/udagram-reverseproxy:v3
