apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: udagram-reverseproxy
