apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    run: udagram-frontend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: udagram-frontend