apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: raoulkuate/udagram-api-feed:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: appconfig
          - secretRef:
              name: dbconfig
        volumeMounts:
          - mountPath: "/root/.aws"
            name: credentials
            readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: awscredentials

        